name: kraken2-bracken-mtg
channels:
  - default
dependencies:
  - conda-forge::libzlib=1.2.13
  - bioconda::kraken2=2.1.2
  - bioconda::bracken=2.8=py310h30d9df9_0
  - bioconda::fastp=0.23.2
  - bioconda::multiqc=1.13
  - conda-forge::r-base=4.2.0
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-remotes=2.4.2
  - conda-forge::pandas=1.5.2
  - conda-forge::biopython=1.80
