name: Docker Image CI

on:
  push:
    branches: [ "main", "dev", "feature/dockerize" ]
    paths: 
     - 'Dockerfile'
     - 'conda.yml'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "kraken2-bracken:$(date +%s)"
        cache-from: type=gha
        cache-to: type=gha,mode=max