name: Docker Image CI

on:
  push:
    branches: ["dev"]
    paths: 
     - 'Dockerfile'
     - 'conda.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
