name: Run Pipeline
on:
  push:
    branches: ["dev", "feature/test-run"]
    
  pull_request:
    branches: ["main"]

jobs:
  fetch-krakendb:
    name: Fetch Kraken Database
    runs-on: ubuntu-20.04
    steps:
      - name: Cache Kraken Database
        id: cache-kraken
        uses: actions/cache@v3
        with:
            path: krakendb
            key: ${{ runner.OS }}-kraken-cache-${{ hashFiles('krakendb') }}
            restore-keys: |
              ${{ runner.OS }}-kraken-cache-
  
      - if: ${{ steps.cache-kraken.outputs.cache-hit != 'true' }}
        name: Download kraken database
        uses: wei/wget@v1
        with:
          args: -O minikraken.tgz https://genome-idx.s3.amazonaws.com/kraken/k2_standard_08gb_20221209.tar.gz
      - if: ${{ steps.cache-kraken.outputs.cache-hit != 'true' }}
        run: | 
          mkdir -p krakendb && cd krakendb && tar -xzf ../minikraken.tgz
